# Generated by Django 5.0.4 on 2024-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarWashBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.CharField(max_length=20)),
                ('packageType', models.IntegerField()),
                ('carwashpoint', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('washtime', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=30)),
                ('adminremark', models.CharField(max_length=50)),
                ('paymentmode', models.CharField(max_length=100)),
                ('postingDate', models.DateField()),
                ('updateDate', models.DateField()),
            ],
        ),
    ]
