# Generated by Django 5.0.4 on 2024-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carwashbooking',
            old_name='date',
            new_name='washdate',
        ),
    ]
